name: Build EXE and Publish Release

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    permissions: write-all
    runs-on: windows-latest  # Use a Windows runner to build the .exe

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the Python version you need

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    # Step 4: Build the EXE
    - name: Build EXE
      shell: cmd
      run: build.bat

    # Step 5: Create a Tag
    - name: Create Tag
      shell: pwsh
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        $VERSION = Get-Content VERSION
        $TAG_NAME = "$VERSION-" + (Get-Date -Format "yyyyMMddHHmmss")
        echo "TAG_NAME=$TAG_NAME" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        git tag -a $TAG_NAME -m "Release $TAG_NAME"
        git push origin $TAG_NAME

    # Step 6: Create a GitHub Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 7: Upload the EXE to the Release
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/usdxfixgap.exe  # Path to the generated EXE
        asset_name: usdxfixgap.exe
        asset_content_type: application/octet-stream